handlers= java.util.logging.ConsoleHandler

.leval = ALL

java.util.logging.ConsoleHandler.leval = ALL
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.Format = [%1$tFT%1$tT][%4$s] %3$s %5$s%6$s%n

org.springframework.level=INFO
com.exemple.demp.level=ALL